version:  '3.2'
services:
# 启动一次备份服务 ./docker-compose restart backup
  backup:
    image: mysql:5.7
    environment:
        MYSQL_HOST: mysql
        MYSQL_DATABASE: package_v1
        MYSQL_USER: root
        MYSQL_PASSWORD: zhaojun
    depends_on:
      - mysql-db
    links:
      - mysql-db:mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/backup:/backup:rw
      - ./dockerfiles/backup/:/app:ro
    entrypoint:
      - /bin/bash
    command: /app/backup-default.sh