version: '3.2'
services:
##附加扩展安装器
##composer构建工具，官方的composer中得php未编译bcmath
  composer:
    #image: composer:1.4.2
    build: ./dockerfiles/composer/
    image: zhaojunlike/composer:5.6-latest

    volumes:
    #网站目录
      - ./app:/app:rw
    working_dir: /app/webroot
    command: composer install

  bower:
    image: digitallyseamless/nodejs-bower-grunt
    volumes:
      - ./app:/app:rw
    working_dir: /app/webroot
    deploy:
      restart_policy:
        condition: none
    command: bower install
